version: '3.4'

networks:
  backend:
    external: true
    
services:      
  db:
    container_name: sql-server-db
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "qwer123*"
      ACCEPT_EULA: "Y"

  apigateway:
    image: apigateway
    container_name: ApiGateway
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - backend
    ports:
      - 5000:80

  customerapi:
    image: customerapi
    container_name: CustomerApi
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
    networks:
      - backend
    ports:
      - 8002:80

  productapi:
    image: productapi
    container_name: ProductApi
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    networks:
      - backend
    ports:
      - 5000:80